apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  namespace: billing-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
        releaseVersion: "v1.0.0"
    spec:
      containers:
      - name: web-app
        image: nginx:1.23.3
        ports:
        - containerPort: 80
          name: httpPort
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
