apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: billing-system
  annotations:
    trafficType: "externalHttp"
spec:
  selector:
    app: web-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: httpPort
  type: ClusterIP
