apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-limits-quota
  namespace: default
  labels:
    quotaScope: "defaultLimits"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "20"
    services: "10"
