apiVersion: v1
kind: Secret
metadata:
  name: app-tls-certs
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEozCCA0ugAwIBAgIQCg==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA0w==
    -----END RSA PRIVATE KEY-----
