apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pod-runner
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/appExecutorRole"
    awsRoleArn: "arn:aws:iam::123456789012:role/appExecutorRole"
  labels:
    activeScope: "productionExecution"
