apiVersion: v1
kind: Namespace
metadata:
  name: restricted-security-zone
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: "v1.33"
    podSecurityStandardsScope: "strictEnforce"
