apiVersion: v1
kind: Service
metadata:
  name: web-api-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: containerPortName
    nodePort: 30080
    name: httpPort
  selector:
    app: web-api
